### ISSUE TITLE
Unnecessary Checks

### ISSUE THREAD

**Issue by Levi-M** [TriCkle-C/Sprinkle#1]
Not sure if you have down syndrome but this is unwanted and pointless:

                if username == '':
			self.send("%xt%e%-1%100%")
			self.transport.loseConnection()
		if not username:
			self.send("%xt%e%-1%100%")
			self.transport.loseConnection()
		if username is None:
			seld.send("%xt%e%-1%100%")
			self.transport.loseConnection()
										
		## Password Check
		
		if password == '':
			self.send("%xt%e%-1%101%")
			self.transport.loseConnection()
		if not password:
			self.send("%xt%e%-1%101%")
			self.transport.loseConnection()
		if password is None:
			self.send("%xt%e%-1%101%")
			self.transport.loseConnection()
		if len(password) < 32:
			self.send("%xt%e%-1%101%")
			self.transport.loseConnection()
		if len(password) < 32:
			self.send("%xt%e%-1%101%")		
			self.transport.loseConnection()		
		

The client automatically does all that.

**Comment by valid22** [comment]
Ok. I'll pull on next merge!
